name: Patch‑Bot

on:
  schedule:
    - cron: "0 2 * * *"       # every night at 02:00 UTC
  workflow_dispatch:         # and let you run it manually

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install pygithub requests

      - name: Run Patch‑Bot
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python patchbot.py
